#include "libslic3r/ExtrudeConfig.hpp"

namespace Slic3r::Biz::Slicing {
ExtrudeConfig::ExtrudeConfig(const Domain::ConfigView& config) :
    default_acceleration{config.get<std::vector<double>>("default_acceleration")},
    first_layer_acceleration{config.get<std::vector<double>>("first_layer_acceleration")},
    first_layer_acceleration_over_raft{
        config.get<std::vector<double>>("first_layer_acceleration_over_raft")
    },
    bridge_acceleration{config.get<std::vector<double>>("bridge_acceleration")},
    top_solid_infill_acceleration{config.get<std::vector<double>>("top_solid_infill_acceleration")},
    solid_infill_acceleration{config.get<std::vector<double>>("solid_infill_acceleration")},
    infill_acceleration{config.get<std::vector<double>>("infill_acceleration")},
    external_perimeter_acceleration{
        config.get<std::vector<double>>("external_perimeter_acceleration")
    },
    perimeter_acceleration{config.get<std::vector<double>>("perimeter_acceleration")},
    perimeter_speed{config.get<std::vector<double>>("perimeter_speed")},
    infill_speed{config.get<std::vector<double>>("infill_speed")},
    solid_infill_speed{config.get<std::vector<Domain::FloatOrPercentage>>("solid_infill_speed")},
    external_perimeter_speed{
        config.get<std::vector<Domain::FloatOrPercentage>>("external_perimeter_speed")
    },
    bridge_speed{config.get<std::vector<double>>("bridge_speed")},
    object_extrusion_ratio{config.get<double>("object_extrusion_ratio")},
    gap_fill_speed{config.get<std::vector<double>>("gap_fill_speed")},
    retract_speed{config.get<std::vector<double>>("retract_speed")},
    retract_lift{config.get<std::vector<double>>("retract_lift")},
    retract_lift_above{config.get<std::vector<double>>("retract_lift_above")},
    retract_lift_below{config.get<std::vector<double>>("retract_lift_below")},
    retract_length{config.get<std::vector<double>>("retract_length")},
    retract_before_travel{config.get<std::vector<double>>("retract_before_travel")},
    travel_max_lift{config.get<std::vector<double>>("travel_max_lift")},
    travel_slope{config.get<std::vector<double>>("travel_slope")},
    travel_ramping_lift{config.get<std::vector<bool>>("travel_ramping_lift")},
    retract_layer_change{config.get<std::vector<bool>>("retract_layer_change")},
    travel_acceleration{config.get<double>("travel_acceleration")},
    travel_short_distance_acceleration{config.get<double>("travel_short_distance_acceleration")},
    max_volumetric_speed{config.get<std::vector<double>>("max_volumetric_speed")},
    filament_max_volumetric_speed{config.get<std::vector<double>>("filament_max_volumetric_speed")},
    filament_infill_max_crossing_speed{
        config.get<std::vector<double>>("filament_infill_max_crossing_speed")
    },
    filament_infill_max_speed{config.get<std::vector<double>>("filament_infill_max_speed")},
    enable_dynamic_overhang_speeds{config.get<std::vector<bool>>("enable_dynamic_overhang_speeds")},
    overhang_speed_0{config.get<std::vector<Domain::FloatOrPercentage>>("overhang_speed_0")},
    overhang_speed_1{config.get<std::vector<Domain::FloatOrPercentage>>("overhang_speed_1")},
    overhang_speed_2{config.get<std::vector<Domain::FloatOrPercentage>>("overhang_speed_2")},
    overhang_speed_3{config.get<std::vector<Domain::FloatOrPercentage>>("overhang_speed_3")},
    enable_dynamic_fan_speeds{config.get<std::vector<bool>>("enable_dynamic_fan_speeds")},
    overhang_fan_speed_0{config.get<std::vector<int>>("overhang_fan_speed_0")},
    overhang_fan_speed_1{config.get<std::vector<int>>("overhang_fan_speed_1")},
    overhang_fan_speed_2{config.get<std::vector<int>>("overhang_fan_speed_2")},
    overhang_fan_speed_3{config.get<std::vector<int>>("overhang_fan_speed_3")},
    gcode_flavor{config.get<Domain::GCodeFlavor>("gcode_flavor")},
    machine_max_feedrate_x{config.get<std::vector<double>>("machine_max_feedrate_x")},
    machine_max_feedrate_y{config.get<std::vector<double>>("machine_max_feedrate_y")},
    machine_max_feedrate_z{config.get<std::vector<double>>("machine_max_feedrate_z")},
    machine_max_acceleration_travel{
        config.get<std::vector<double>>("machine_max_acceleration_travel")
    },
    machine_max_acceleration_z{config.get<std::vector<double>>("machine_max_acceleration_z")},
    machine_max_jerk_z{config.get<std::vector<double>>("machine_max_jerk_z")},
    fill_density{config.get<std::vector<Domain::Percentage>>("fill_density")},
    z_offset{config.get<double>("z_offset")},
    travel_speed{config.get<double>("travel_speed")},
    ironing_speed{config.get<double>("ironing_speed")},
    support_material_speed{config.get<double>("support_material_speed")},
    support_material_interface_speed{
        config.get<Domain::FloatOrPercentage>("support_material_interface_speed")
    },
    over_bridge_speed{config.get<std::vector<Domain::FloatOrPercentage>>("over_bridge_speed")},
    top_solid_infill_speed{
        config.get<std::vector<Domain::FloatOrPercentage>>("top_solid_infill_speed")
    },
    first_layer_infill_speed{
        config.get<std::vector<Domain::FloatOrPercentage>>("first_layer_infill_speed")
    },
    first_layer_solid_infill_speed{
        config.get<std::vector<Domain::FloatOrPercentage>>("first_layer_solid_infill_speed")
    },
    first_layer_perimeter_speed{
        config.get<std::vector<Domain::FloatOrPercentage>>("first_layer_perimeter_speed")
    },
    first_layer_external_perimeter_speed{
        config.get<std::vector<Domain::FloatOrPercentage>>("first_layer_external_perimeter_speed")
    },
    first_layer_support_material_speed{
        config.get<std::vector<Domain::FloatOrPercentage>>("first_layer_support_material_speed")
    },
    first_layer_top_solid_infill_speed{
        config.get<std::vector<Domain::FloatOrPercentage>>("first_layer_top_solid_infill_speed")
    },
    first_layer_gap_fill_speed{
        config.get<std::vector<Domain::FloatOrPercentage>>("first_layer_gap_fill_speed")
    },
    first_layer_speed_over_raft{
        config.get<std::vector<Domain::FloatOrPercentage>>("first_layer_speed_over_raft")
    },
    avoid_crossing_perimeters_max_detour{
        config.get<double>("avoid_crossing_perimeters_max_detour")
    },
    gcode_comments{config.get<bool>("gcode_comments")},
    arc_fitting{config.get<Domain::ArcFittingType>("arc_fitting")},
    scarf_seam_placement{config.get<Domain::ScarfSeamPlacement>("scarf_seam_placement")},
    only_retract_when_crossing_perimeters{
        config.get<bool>("only_retract_when_crossing_perimeters")
    },
    avoid_crossing_perimeters{config.get<bool>("avoid_crossing_perimeters")},
    avoid_crossing_curled_overhangs{config.get<bool>("avoid_crossing_curled_overhangs")}
{}

} // namespace Slic3r::Biz::Slicing
